"""Add user persona

Revision ID: 61c0e6da255a
Revises: 8be47d73fb60
Create Date: 2026-06-02 15:20:58.919351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c0e6da255a'
down_revision: Union[str, None] = '8be47d73fb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personas',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expertise_level', sa.String(), nullable=True),
    sa.Column('response_style', sa.String(), nullable=True),
    sa.Column('interests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('recent_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('topic_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_personas')
    # ### end Alembic commands ###
